### PR TITLE
Make h5py imports fail late.

### PR DESCRIPTION
**Pull request by juanchopanza**
This may sound crazy but there is a rationale behind it: in the current
neurom.io design, SWC and HDF5 readers are imported early. But HDF5 may
be considered an internal BBP format, and most external users may not
need it. Ideally, the IO should use a plug-in architecture to make the
optionality of readers more explicit.

TODO: This isn't correctly tested in the absence of h5py. Figure out how
to test it.

### CODE REVIEW

**Comment by juanchopanza** [comment]
@mgeplf @wvangeit this is for issue #130. It is an awful hack, so if you have better ideas on how to do this I am all ears. I would like to make the IO use plugins at some point in the future, but we're not there yet.

**Comment by wvangeit** [comment]
Is this mock H5 class necessary ? Can't you just check if h5py is available during import in hdf5.py, and print a clear error message saying that neurom has to be install with 'pip install neurom[hdf5] to enable this functionality ? 
To prevent hdf5.py being loaded unwillingly reader.py could only execute 'from neurom.io.hdf5 import H5' when somebody attemps to load an h5 file.

**Comment by juanchopanza** [comment]
The mock is so I can keep the structure of the reader unchanged. I will have a look at what you suggest but I am not sure it is worth the changes it would require.

**Comment by juanchopanza** [comment]
@wvangeit I followed your advice in the end and simplified this. It seems to work fine, although it isn't fully tested.

**Comment by juanchopanza** [comment]
Unless I have any objections by 11AM, I will merge this.

**Comment by mgeplf** [comment]
+2 from me

**Comment by wvangeit** [comment]
Looks ok to me

**Comment by juanchopanza** [comment]
Fixes #130

**Pull request merged**
