### PR TITLE
fix: local bifurcation angle calculation for zero length segments

### LINKED ISSUE #285: How to calculate a bifurcation angle when one or both children are zero distance from their parent
The bifurcation angle is defined as the angle between the lines connecting a parent point to its two child points in a morphology. We explicitly exclude multifurcations beyond two. Many biological cells have artifacts in which one or both children are at zero distance from their parent. We do not want to reject these points in calculating the bifurcation angles as they often constitute a large subset of any neuron's bifurcation points.

A simple solution is to make a check when calculating a bifurcation angle:

if( both children are greater than epsilon from their parent)
    calculate bifurcation angle using the two vectors from parent to the children
else if( one or both children are less than epsilon from their parent)
    replace the child of zero length with its own child if it is unique; if one child is itself a bifurcation ignore it.

    if( both these children exist)
       calculate the bifurcation angle using these children/grandchildren
    else
       // one child must be a termination
       do not count this point as a bifurcation

### PR DESCRIPTION
**Pull request by juanchopanza**
Algorithm now searches for first point in child section(s) such
that the bifurcation start - end points aren't the same.

Fixes #285.

### CODE REVIEW

**Comment by juanchopanza** [comment]
@berthelm @lidakanari this should fix the issue when points daughter points have exactly the same coordinates as the parent. Could someone check if the zeros disappear?

**Comment by lidakanari** [comment]
OK, I will run it with bio cells and confirm the status of the output.

**Comment by juanchopanza** [comment]
I will merge this. Then if there are still problems, I may add a point equality tolerance parameter.

**Comment by lidakanari** [comment]
I think all is good now! Problem fixed:
figure_1

**Pull request merged**
