### PR TITLE
Update example astrocyte analysis notebook

### PR DESCRIPTION
**Pull request by pgetta**
* Make the notebook work with the latest NeuroM
* Add astrocyte selection and download from NGV static server
* Make figures larger

### CODE REVIEW

**Review by asanin-epfl — APPROVED** [review]

**Comment by asanin-epfl** [comment]
you can use plotly if you want plots to be nicer, scalable, manipulable by user.

**Comment by pgetta** [comment]
That would be really nice, do you have by any chance an example how this can be done?

**Comment by asanin-epfl** [comment]
a neighbor tutorial `getting_started.ipynb` contains examples of plotly graphics in the beginning.

**Comment by asanin-epfl** [comment]
Also would be good to rename `Neuron id` to `Astrocyte id` in "Morphology Analysis" paragraph.

**Comment by pgetta** [comment]
Thank you, Aleksei,
Indeed, plotly works better for this case, I've also renamed neuron to astrocyte in the morphology analysis paragraph.

Anything else of concern?

**Review by asanin-epfl — APPROVED** [review]
no, everything should be fine by now

**Comment by pgetta** [comment]
Thanks!

**Pull request merged**
