### PR TITLE
Fix uniform paramaters fit.

### PR DESCRIPTION
**Pull request by lidakanari**

### CODE REVIEW

**Comment by lidakanari** [comment]
This should fix a scipy bug that returns the parameters of uniform distribution in random order, and the problem that @juanchopanza mentioned about setting min-max twice.

**Comment by juanchopanza** [comment]
I guess the JSON file is added by accident? For the .py file, I have a related change, see #115

**Comment by lidakanari** [comment]
Removed json file.

**Comment by juanchopanza** [comment]
Looks good, but I think the changes in #115 supersede this.

**Comment by juanchopanza** [comment]
Closing as superseded by #115

**Pull request closed without merging**
