### PR TITLE
Simplify neurite feature extraction code.

### PR DESCRIPTION
**Pull request by juanchopanza**
* Remove as_neurite_list decorator, which had redundant
  functionality wrt neurom.iter_neurites.

### CODE REVIEW

**Comment by juanchopanza** [comment]
@eleftherioszisis @lidakanari This is a start. There is a lot more to simplify here. I will continue removing stuff in future pull requests. In the meantime, it would be great if somebody could add tests for the neurite features map, because that is what people would be using.

**Comment by lidakanari** [comment]
Looks good. Thanks! I'll try to add some tests later if I have time.

**Comment by juanchopanza** [comment]
@lidakanari I need to know if you can add the tests by tomorrow or not. Otherwise I will do it.

**Comment by lidakanari** [comment]
I don't have too much time to work on this right now. If you want you can add the tests and I will check them in the follow up review. Does that work for you?

**Comment by juanchopanza** [comment]
Sure. I will just change the tests that test the functions directly.

**Comment by lidakanari** [comment]
Ok, here's an example of what I had in mind for a test:

np.allclose(NEURITEFEATURES['section_lengths'](n), sec.length(...))

**Comment by juanchopanza** [comment]
You can add more tests later if you want. i will just translate what is already there.

**Comment by lidakanari** [comment]
Ok, that works for me. Thanks!

**Pull request merged**
