### PR TITLE
morph_stats config can now handle and output a 'soma' block

### PR DESCRIPTION
**Pull request by wizmer**
Issue https://github.com/BlueBrain/NeuroM/issues/678

Soma properties can be specified in the 'neuron' block (legacy)

```
{
    'neuron': {
        'soma_radii': ['mean'],
    }
}
```

or in the 'soma' block:
```
{
    'soma': {
        'soma_radii': ['mean'],
    }
}
```

Which block was used (whether neuron or soma) will be reflected in the
output json.

### CODE REVIEW

**Comment by arnaudon** [comment]
What about adding soma as another neurite_type?

**Comment by asanin-epfl** [comment]
@arnaudon would you need this one? Otherwise I will close it.

**Comment by arnaudon** [comment]
pfiuuuu, I completely forgot about that one, I think the soma things are now in neuron entry or something. Let's drop that, and we'll make another one more up to date if we need to.

**Comment by asanin-epfl** [comment]
thanks for clarifying

**Pull request closed without merging**
