### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alex4200**
Update to the final(?) copyright version?

### CODE REVIEW

**Comment by asanin-epfl** [comment]
just week ago #896 was merged, @ASVG  please advice

**Comment by asanin-epfl** [comment]
what's the status here? @alex4200 @ASVG

**Comment by alex4200** [comment]
this should be merged

**Comment by asanin-epfl** [comment]
Since @ASVG does not respond, I'm merging

**Review by asanin-epfl — APPROVED** [review]

**Pull request merged**
