### PR TITLE
Beta Neurolucida ASCII parser for v3 files

### PR DESCRIPTION
**Pull request by mgeplf**
* written by only examining the output of *.asc files
* not sure it's 100 percent correct
* could be written more performantly

### CODE REVIEW

**Comment by lidakanari** [comment]
Wow!!! That's great! I will try it with a couple of examples and I'll let you know :)

**Comment by juanchopanza** [comment]
What does "v3" correspond to? AFAIK there are different neurolucidas around, so it would be good to know what kind of files precisely this can parse. Is there any resource we can refer to for a "spec", no matter how loose? Or is the idea to eventually come up with a spec?

**Comment by mgeplf** [comment]
The comments on the file I was reversing from said
';	V3 text file written for MicroBrightField products.'

I don't have any spec, that's why I had to reverse it.

Can you point me to these different neurolucidas?

**Comment by juanchopanza** [comment]
I can't, but it is what I have heard whenever we discuss standardized morphology formats. Think of it as XML with many different schemas. That don't exist. I think Julian, Lida and/or Jean-Denis might have more info.

**Comment by lidakanari** [comment]
Sorry, but I am not aware of any official specs of neurolucida ascii format. Julian has a spec for the xml but I'm not sure if we can transform this to an ascii equivalent.

**Comment by juanchopanza** [comment]
@lidakanari do you have any comments on the "many neurolicida's" issue?

**Comment by lidakanari** [comment]
Unfortunately, we find those by trial and error and there are no specific 'versioning' of different files. Also, I fail to run the neurolucida module correctly 

```python
In [1]: import neurom.io.neurolucida as nasc
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-87a87bcfe68f> in <module>()
----> 1 import neurom.io.neurolucida as nasc

ImportError: No module named neurolucida
```
So I can't really test the files I have. 

Running the tests I also get this error:
```
======================================================================
ERROR: test_neurolucida.test__parse_section
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kanari/github/Experimental_ready/Mike/NeuroM/neurom_test_venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/kanari/github/Experimental_ready/Mike/NeuroM/neurom/io/tests/test_neurolucida.py", line 32, in test__parse_section
    with patch('neurom.io.nasc._match_section') as mock_match:
  File "/home/kanari/github/Experimental_ready/Mike/NeuroM/neurom_test_venv/local/lib/python2.7/site-packages/mock/mock.py", line 1353, in __enter__
    self.target = self.getter()
  File "/home/kanari/github/Experimental_ready/Mike/NeuroM/neurom_test_venv/local/lib/python2.7/site-packages/mock/mock.py", line 1520, in <lambda>
    getter = lambda: _importer(target)
  File "/home/kanari/github/Experimental_ready/Mike/NeuroM/neurom_test_venv/local/lib/python2.7/site-packages/mock/mock.py", line 1210, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/home/kanari/github/Experimental_ready/Mike/NeuroM/neurom_test_venv/local/lib/python2.7/site-packages/mock/mock.py", line 1199, in _dot_lookup
    __import__(import_path)
ImportError: No module named nasc
```

**Comment by mgeplf** [comment]
Fixed the typo in my mock signature.

The import seems to work for me.

**Comment by orena1** [comment]
I once asked MicroBrightField, Inc. about the specification of the asc files, I got the following response 

> Hi Oren,
>  
> The ASC file format for Neurolucida is not a public file format and we don’t actually have any written specification for it.
>  
> Do  you have specific questions I might be able to help answer?
>  
> Best,
>  
>            Geoff (geoff@mbfbioscience.com)

I hope it helps.

**Comment by lidakanari** [comment]
Thanks Oren! So, we have an official confirmation that we are lacking any official specs. 

I tested a couple of datasets and the loader seems quite decent. Since we don't have any good tool for the conversion, I can't verify specific results. What I am planning to do is to manually transform the Neuron.swc in neurolucida ascii and provide some comparative tests. However, this will take a while so I would suggest we merge the changes and correct anything that needs to be fixed in a subsequent pull request.

**Comment by juanchopanza** [comment]
Given that it is hard to cross-validate this, and that there is no specification, I think at the very least we need to emit a warning that the parser if not designed to work with arbitrary NL ascii files. If possible, we should also come up with a spec of what this parser *does* support.

**Comment by orena1** [comment]
As neurolucida software also have option to run analysis on morphologis and output features (soma size, dendritic length etc..) it might be possible to cross validate by checking that the features from NeuroM and from neurolucida are equal. (I do not have neurolucida licence... )

**Pull request merged**
