### PR TITLE
Table of plots for feature and cells

### PR DESCRIPTION
**Pull request by eleftherioszisis**
This example  covers for:

A) A table where each row is a feature and the columns are graphs of that feature for the cell created by different reconstruction algorithms (this compares many features from many different reconstruction algorithms for the same cell)

B) Superimposition of a selected feature graph for a set of reconstructed cells  (this could be either one cell reconstructed by many different algorithms, or different instances of the same algorithm on different image stacks). 

Please let me now if power ups are needed!

### CODE REVIEW

**Comment by juanchopanza** [comment]
Looks fine to me but I don't know much matplotlib. @lidakanari can you have a look?

**Comment by eleftherioszisis** [comment]
I will need to do some changes tomorrow, so do not merge it yet.

**Comment by lidakanari** [comment]
Ok, so we need to add a couple of more features-capabilities but it is good in general. We can work on the details later!

**Comment by eleftherioszisis** [comment]
@juanchopanza I will remove the main and enable the user to call it without editing the file, so do not merge yet. (I have to meet with Giuseppe so it might take some time)

**Comment by eleftherioszisis** [comment]
Ok, I added the argparse stuff. @lidakanari  is it sufficient or should I add sth else as well?

**Comment by lidakanari** [comment]
Looks good to me! @juanchopanza you can merge it and we correct details in the future versions according to our needs.

**Pull request merged**
