### PR TITLE
remove NeuriteType.all from NEURITES

### PR DESCRIPTION
**Pull request by asanin-epfl**
Solution to #804

### CODE REVIEW

**Review by arnaudon — APPROVED** [review]
I don't use .all, so I'm good, but I'm not aware of all possible usecases.

**Comment by asanin-epfl** [comment]
> I don't use .all, so I'm good, but I'm not aware of all possible usecases.

I understand. That's why I've added all concerning parties as reviewers here.

**Review by adrien-berchet — APPROVED** [review]
As far as I can see, only NeuroM is using `.all`, so we will just need a new version of NeuroM compatible with this PR.

**Comment by arnaudon** [comment]
But this is NeuroM, stop working so late :P

**Comment by adrien-berchet** [comment]
Indeed... 🤦😁
I don't know why I though I was on morph-tool :-)

**Comment by asanin-epfl** [comment]
Thank you!

**Pull request merged**
