### PR TITLE
Ensure angle_between_vectors() always return 0 when the vectors are equal

### PR DESCRIPTION
**Pull request by adrien-berchet**

### CODE REVIEW

**Comment by mgeplf** [comment]
This looks reasonable to me, perhaps you can have a final look @asanin-epfl ?

**Review by asanin-epfl — COMMENTED** [review]
Please add an entry for Version 3.0.1 in CHANGELOG

**Review by asanin-epfl — APPROVED** [review]

**Comment by asanin-epfl** [comment]
Will you need a release? I saw other PRs that depend on this one.

**Comment by adrien-berchet** [comment]
As far as I am concerned, we can wait for this one for a new release: https://github.com/BlueBrain/NeuroM/pull/956

**Pull request merged**
