### PR TITLE
Add segment x, y, z coordinates and radii features

### PR DESCRIPTION
**Pull request by lidakanari**
This solves #288 and it is crucial for the simplification of plotting and constructing more complex measurements.

### CODE REVIEW

**Comment by eleftherioszisis** [comment]
Seems fine to me!

**Comment by juanchopanza** [comment]
I think it would be much simpler to calculate the "position" of a segment as the 3D mean of its two points, and *maybe* add helper functions to extract X, Y, and Z. Having three separate functions everywhere seems like too much. For example

    def segment_position(seg):
        return (seg[0][:COLS.R] + seg[1][1:COLS.R]) / 2.

Then, if you really want separate "features" for each coordinate, then it is three loops.

**Comment by lidakanari** [comment]
For what I need those functions, the three coordinates need to be separated. I don't want to do all the calculations each time I only need the projection in x for example, that's why I disconnect the coordinates.

**Comment by juanchopanza** [comment]
OK. It looks like a lot of code for something really simple. I will merge it and try to reduce it later.

**Comment by lidakanari** [comment]
Yes, that's True. I just want to avoid expensive calculations in intermediate steps that will not be used in the final step. If you have a better alternative please go ahead and simplify it.

**Pull request merged**
