### PR TITLE
Merge pull request #1 from BlueBrain/master

### PR DESCRIPTION
**Pull request by liesbethvanherpe**
Pulling in 6 commits

### CODE REVIEW

**Comment by juanchopanza** [comment]
Not really sure what happened here. There are no file changes associated to this pull request.

**Comment by liesbethvanherpe** [comment]
Me neither. I wanted to pull in the latest version of neurom in my fork, but I may have done something else.

**Comment by juanchopanza** [comment]
Ah OK, looks like you pulled in the wrong direction!

**Comment by liesbethvanherpe** [comment]
That's probably it. I don't need a jetlag for that.

**Pull request merged**
