### PR TITLE
Update jupyter notebook to use newest code

### PR DESCRIPTION
**Pull request by juanchopanza**

### CODE REVIEW

**Comment by juanchopanza** [comment]
@eleftherioszisis @lida This may be of interest. I think we hadn't checked the notebook for a long while!

**Comment by lidakanari** [comment]
Thanks @juanchopanza ! I can't make comments on the changes, but I only see a few "simple" issues... I could take a look once you merge and correct some of them.

**Comment by juanchopanza** [comment]
@lidakanari OK, I will merge this and we can improve it in a further iteration.

**Comment by lidakanari** [comment]
OK, I will try to correct a few trivial mistakes now that I remember them :)

**Pull request merged**
