### PR TITLE
More reconciliation with mut_morphio

### PR DESCRIPTION
**Pull request by wizmer**
This brings more formatting of the test file

### CODE REVIEW

**Comment by wizmer** [comment]
Sorry for those uninteresting PRs Aleksei...

**Review by asanin-epfl — APPROVED** [review]
I'm curious. When I had an interesting one? :D

**Comment by wizmer** [comment]
Thanks. I have more coming, don't worry !

**Comment by asanin-epfl** [comment]
Yes! More uninteresting PRs for uninteresting Aleksei!

**Pull request merged**
