### PR TITLE
Section tree module

### PR DESCRIPTION
**Pull request by juanchopanza**
Section tree has soma and has been moved to its own module.

### CODE REVIEW

**Comment by juanchopanza** [comment]
@eleftherioszisis @lidakanari I have implemented many "features" using the section tree, but the functions currently only work for a single neuron. If either of you have the time to try this out it woudl be great. I think I covered all the features used in the m30 synthesis validation.

**Comment by eleftherioszisis** [comment]
Do you want to test something in particular or just load and run some analysis?

**Comment by juanchopanza** [comment]
@eleftherioszisis If you have something you can run it would be good to see how much faster it is. BTW I _think_ the feature functions would work with populations too, at least for neurite features.

**Comment by eleftherioszisis** [comment]
I can run it on the same population of 1000 cells that I posted before and see what happens :P

**Comment by eleftherioszisis** [comment]
(Although I don't have a comparison for analysis apart from the big cell)

**Comment by juanchopanza** [comment]
OK, sounds good. You may need to write a `load_population` function calling `section_neuron.load_neuron`. Maybe try a smaller sample first!

**Pull request merged**
