### PR TITLE
fix: branch order starts at 0 from root

### LINKED ISSUE #295: Bug in Branch order definition
I found a reference to the definition of branch order : http://www.sciencedirect.com/science/article/pii/0165027086901160

screenshot from 2016-04-13 11 52 45

According to this paper, which is used as reference in Neurolucida as well, branch order starts from 0. In our implementation, branch order starts from -1 at the root. Example:

```python
n = ezy.load_neuron('./NeuroM/test_data/swc/Neuron.swc')

nf['section_branch_orders'](n)

Out[4]: array([-1.,  0.,  0.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,
        6.,  6.,  7.,  7.,  8.,  8.,  9.,  9., -1.,  0.,  0.,  1.,  1.,
        2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,  7.,  8.,
        8.,  9.,  9., -1.,  0.,  0.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,
        4.,  5.,  5.,  6.,  6.,  7.,  7.,  8.,  8.,  9.,  9., -1.,  0.,
        0.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,
        7.,  7.,  8.,  8.,  9.,  9.])
```
It will be better to be consistent with this definition and to add the reference to the implementation of the code.

### PR DESCRIPTION
**Pull request by juanchopanza**
Previously branch order was counted from first child, effectively
setting the root branch order to -1.

Fixes #295

### CODE REVIEW

**Comment by juanchopanza** [comment]
@lidakanari This should do the trick.

**Comment by liesbethvanherpe** [comment]
Should you put a reference to the paper @lidakanari mentioned somewhere? (http://dx.doi.org/10.1016/0165-0270(86)90116-0)

**Comment by juanchopanza** [comment]
I'm not sure it is necessary. It is just a numbering scheme. And I'm not going to read the paper!

**Comment by liesbethvanherpe** [comment]
That's fine with me.

**Comment by lidakanari** [comment]
OK, this looks good to me. Thanks!

**Pull request merged**
