### PR TITLE
morph_stats now can treat multiple directories as populations of neurons

### PR DESCRIPTION
**Pull request by eleftherioszisis**
Multiple directories can be provided as args in morph_stats. if --dir_as_pop is enabled then each directory is treated as a population and the stats are extracted population-wise.

Otherwise, a list with all the filenames in all directories is created and the stats that are extracted are neuron-wise.

### CODE REVIEW

**Comment by juanchopanza** [comment]
What happens if we want to treat all the filenames in all the directories as a single population? I take it there is a difference between population and collection of neurons, or do these boil down to the same at the moment?

**Comment by juanchopanza** [comment]
The stuff in apps is not tested, so I think we should have **less** code in there. For example, all the stats calculating stuff should go in a module and be tested.

**Comment by eleftherioszisis** [comment]
Hmm, there is no option right now that all the files in all directories can be treated as a single population. I thought that the user can put a population inside a directory. For example, if they have a population of cells from a reconstruction, probably it will be inside a folder. If they have multiple reconstructions, i.e. multiple folders then they will be able either parse all their cells for analysis in a single cell basis or treat each directory as a single collection/population and by extension extract morphometrics with respect to each reconstruction.

I agree for the testing of the stats.

**Comment by juanchopanza** [comment]
Maybe the population / collection of neurons - one directory / many directories problem can be split into more orthogonal options

* `as-population` (else treat as collection of neurons)
* `single-group` (all directories treated as one)

OTOH, if populations and single neurons are different, population vs. collection of neurons should not be mutually exclusive. The user should be able to pick one of them or both (and stats that are equivalent between the two should not be duplicated.)

**Comment by juanchopanza** [comment]
Bear in mind that users might want to split an analysis into many jobs. So we could have many jobs running population stats on single directories, and then the data being aggregated over jobs. So it makes sense that a single directory is just a sub-set of many directories, and not something totally different.

**Comment by eleftherioszisis** [comment]
I made the code more compact and now if the as-population flag is provided then the directories are treated as populations but if single files are provided as well then they are processes as single neurons. Thus in the resulting json populations and single neurons can coexist for comparison etc.

@juanchopanza can you please take a look on the layout of the code and give me some directions as to how can I achieve the data aggregation over multiple jobs? (In other words I am not sure that I understood your previous comment, thus I need more info)

**Comment by juanchopanza** [comment]
I think if N files can be input into the application, whether they are treated as a population or as a collection of single neurons should depend on the flag, not on whether the files are in a directory. So I should be able to pass a list of files and have them treated as a population. Otherwise it is too confusing. Currently I think you can pass many files, set the `--as-population` flag, and the neurons don't get treated as a population.

As for data aggregation, it really depends on the type of stats being collected. There isn't a general way to aggregate, but let's assume for now that the users know how to deal with multiple output JSON files. In the future, we may have to have different output for parallelized jobs. But for now I think it is enough to let the user make a population out of the stuff in a single directory (and a list of input files, as mentioned in the previous paragraph.)

**Comment by eleftherioszisis** [comment]
Ok now the app takes a single path as input and depending on the flag --as-population treats its contents (if a dir) separately or as population if it's false or true respectively.

This is the simplest form of the file and I think it's easy to run multiple jobs for different directories. One thing that we might need to think is how we separate in multiple jobs thousands of files that reside in one directory.

**Comment by juanchopanza** [comment]
In that case, this comment has to be fixed:

    help='Paths to morphology data files or directories'

Also, better check with @lidakanari whether we want to lose the ability to deal with more than one population in a single job. It isn't clear to me that we want to stop doing that (assuming it worked before.)

**Comment by eleftherioszisis** [comment]
Oops, yep you're right

**Comment by lidakanari** [comment]
Is this ok, because I will need to work on the same files?

**Comment by eleftherioszisis** [comment]
From my part it is :P

**Comment by juanchopanza** [comment]
@lidakanari It is OK if you think it is OK that we can't analyse more then one population with this script.

**Comment by lidakanari** [comment]
No problem as it is. We can easily generalize this for more directories if we need to (in a future commit).

**Pull request merged**
