### PR TITLE
refactor all neuron names to morphology names

### PR DESCRIPTION
**Pull request by asanin-epfl**
This PR is merging into `3.0.0` branch. Let me know your feedback on it.

- Rename all 'neuron' names to 'morphology' names, including module and package names. Previous
  'neuron' names still exist but deprecated. It is recommended to use new names:

    - ``neurom.check.neuron_checks`` => ``neurom.check.morphology_checks``, replace `neuron_checks`
      with `morphology_checks` in configs for ``neurom check``. This replacement is required as the
      previous 'neuron' name wasn't preserved.
    - ``neurom.core.neuron`` => ``neurom.core.morphology``
    - ``neurom.core.neuron.Neuron`` => ``neurom.core.morphology.Morphology``
    - ``neurom.core.neuron.graft_neuron`` => ``neurom.core.morphology.graft_morphology``
    - ``neurom.io.utils.load_neuron`` => ``neurom.io.utils.load_morphology``
    - ``neurom.io.utils.load_neurons`` => ``neurom.io.utils.load_morphologies``

- Drop 'func' suffix of all module names within `features` package. This rename is not backward compatible.
    - ``neurom.features.bifurcationfunc`` => ``neurom.features.bifurcation``
    - ``neurom.features.sectionfunc`` => ``neurom.features.section``
    - ``neurom.features.neuritefunc`` => ``neurom.features.neurite``
    - ``neurom.features.neuronfunc`` => ``neurom.features.morphology``

### CODE REVIEW

**Comment by arnaudon** [comment]
@asanin-epfl , I won't be able to review anything before second week of august, after I'm back!

**Comment by asanin-epfl** [comment]
Let me know what you think about non backward-compatible changes of `features` package and `neuron_checks` module. If you used `features` via `features.get` then you won't notice breaking changes in that package.

**Comment by adrien-berchet** [comment]
IMO the `features` package looks much better now. And as far as I know we mainly use `features.get` in our codes so it should not break much.

**Comment by asanin-epfl** [comment]
Thank you. I'm glad you like it. I suggest to approve and merge this PR. The main PR #950 of 3.0.0 should be the place for further discussions.

**Review by adrien-berchet — APPROVED** [review]

**Comment by asanin-epfl** [comment]
Thank you

**Pull request merged**
