### PR TITLE
remove unused log.py

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Comment by juanchopanza** [comment]
Note that this had been added to make it easy for users to set up a logger by importing this module. Logging messages were being lost.

**Comment by mgeplf** [comment]
Hmm, I don't see references to it in the docs, and it seems that no tests were covering it, so I didn't think it was being used.

**Comment by juanchopanza** [comment]
Yes, it seems I never got round to documenting this. I think there used to be an example at some point. Do you know of a simpler or more idiomatic way of achieving the same?

**Comment by mgeplf** [comment]
My personal preference is to put this as an example in the documentation, and then point users to the official python documentation for more logging information.

**Pull request merged**
