### PR TITLE
rename ``Population.somata`` to ``Population.soma``

### PR DESCRIPTION
**Pull request by asanin-epfl**
to have name consistency among ``Population`` and ``Neuron``.

### CODE REVIEW

**Comment by adrien-berchet** [comment]
As for #935 , could we have a first version with the two properties and a deprecation warning please?
Also, could we group all these breaking changes in the same version? So we will have only one big update to do when it will be released.

**Review by adrien-berchet — APPROVED** [review]
Thanks!

**Comment by eleftherioszisis** [comment]
May I ask why these two fundamentally different entities need to have common signatures? Population.soma is a confusing combination, isn't it?

**Comment by asanin-epfl** [comment]
I saw that Population and Neuron has the same `neurites` property for features mechanism. So, I thought to make the similar approach for `soma`. Anyway, I can revert.
Can you clarify that `somata` aimed to empasize plural somas at Population? Should we rather call it `somas` then? Is `somata` an official name for plural somas?

**Comment by eleftherioszisis** [comment]
`neurites` property is the same for both `Population` and `Neuron` because even a single neuron has a collection of neurites. However, a Neuron has only one soma, while the Population one soma per Neuron. This is why I find the combination of singular soma and plural Population misleading.

And yeah "soma" is a greek word and its plural is indeed "somata", not "somas". ^^

**Comment by asanin-epfl** [comment]
good then, I'm reverting

**Comment by eleftherioszisis** [comment]
I apologize for not noticing this PR earlier.. :(

**Comment by asanin-epfl** [comment]
No worries. From now on I will put you as a reviewer. Thanks for clarifying.

**Comment by adrien-berchet** [comment]
> And yeah "soma" is a greek word and its plural is indeed "somata", not "somas". ^^

Ah I did not know that! Thanks for the greek course :)

**Comment by asanin-epfl** [comment]
> Ah I did not know that! Thanks for the greek course :)

That caught me as well. I always thought `somata` is more like official name for `soma` e.g. more biological, including all organelles and stuff.

**Pull request merged**
