### PR TITLE
Refactor some morpology checks.

### PR DESCRIPTION
**Pull request by juanchopanza**
Modified neurite monotonicity and flatness checks woth the following
considerations:

* Tests with names such as has_x return True or False.
* Where possible, write has_x tests for which True is good, False is
  bad.
* Provide getter functions to get lists of "bad" neurites

### CODE REVIEW

**Comment by juanchopanza** [comment]
@jdcourcol @eleftherioszisis @lidakanari This might be of interest. I will add a test for number of flat neurites in a future commit. That will allow for different configurations to test for different flatness criteria.

**Comment by juanchopanza** [comment]
Any comments / objections?

**Comment by lidakanari** [comment]
It seems ok to me, but I would wait for Eleftherios to check the details.

**Comment by eleftherioszisis** [comment]
I think it is good. Now it is much clearer to the user, what the functions do!

**Comment by juanchopanza** [comment]
OK, thanks. I will merge this.

**Pull request merged**
