### PR TITLE
Cleaning view code and adding aspect ration option, as requested in  #279

### PR DESCRIPTION
**Pull request by lidakanari**
Choose aspect_ratio = 'equal' to set the aspect ratio of the figure.

### CODE REVIEW

**Comment by lidakanari** [comment]
Check this @wvangeit, @chalimou, @romani79, @eleftherioszisis :

Please let me know which value I should set to default if you have any preference. Examples of 'normal' versus 'equal' aspect_ratio:

normal

equal

**Comment by lidakanari** [comment]
This fixes  #279

**Comment by chalimou** [comment]
I’m not an expert but I think equal ratio as default makes more sense,

nancy

**Comment by juanchopanza** [comment]
@lidakanari Looks OK to me. Let me know whenever this is ready to be merged.

**Comment by lidakanari** [comment]
OK, I will change the default value and I'll let you merge it.

**Comment by lidakanari** [comment]
It should be good now, if there are no errors in CI.

**Comment by wvangeit** [comment]
Yep, equal aspect ratio made most sense indeed

**Comment by romani79** [comment]
I absolutely agree with Werner

**Comment by lidakanari** [comment]
OK, done :) Let me know if it works for you!

**Pull request merged**
