### PR TITLE
2.4.0

### PR DESCRIPTION
**Pull request by asanin-epfl**
This is a PR for version 2.4.0. It includes the PRs:
- refactor viewer (#935)
- Refactor features. (#939)
- Delete deprecated neurom.features.register_neurite_feature (#940)
- Stats with args (#942) 

For details see the changes of `CHANGELOG.rst`.

I might include another PR here but anyway it is ready for your detailed review, and I'm open to your questions. Don't rush with the review. I plan to release this after the 5th of July.

### CODE REVIEW

**Comment by adrien-berchet** [comment]
Thanks @asanin-epfl !
I am just wondering if such release with several breaking changes should not be a major release, so v3 instead of v2.4? Because in several codes we have the requirement as `neurom>=2,<3` so they would not break until we update them to work with this new release. WDYT?

**Comment by asanin-epfl** [comment]
>  so v3 instead of v2.4? 

One thing that blocks me from that is #918 . I plan to make the very breaking change and rename all `neuron` names to `morph` names. I plan to use 3.0 for that. 2.4.0 should work because only plotting changes are breaking (I hope not much people use plotting). Other things only get deprecated.
Also I don't want to merge all changes including #918 in one big 3.0. Because I want to delete deprecated stuff in 3.0. There will be much of it.

**Comment by adrien-berchet** [comment]
Ok I see
But does anybody needs these changes before what you want to introduce in v3? If not, why do you mind making a bigger v3 in which deprecated stuffs are removed and all these breaking changes are grouped?

**Comment by asanin-epfl** [comment]
>  If not, why do you mind making a bigger v3 in which deprecated stuffs are removed and all these breaking changes are grouped?

If you are fine with it then I can make it. A huge v3 with all deprecated stuff removed and `neuron` renamed to `morphology`. Please confirm once more that you are ok with that.

**Comment by adrien-berchet** [comment]
I think it would be easier for me to have only one big change to do, what do you think @arnaudon and @eleftherioszisis ?

**Comment by arnaudon** [comment]
+1 for a big release, so we are safe on some codes with <3 m thank you!

**Comment by eleftherioszisis** [comment]
I agree that we should not have breaking changes in a minor version release.

**Pull request closed without merging**
