### PR TITLE
refactor viewer

### PR DESCRIPTION
**Pull request by asanin-epfl**
Solution to #593

- delete `neurom.viewer`
- rename `neurom.view.view` to `neurom.view.matplotlib_impl`
- rename `neurom.view.plotly` to `neurom.view.plotly_impl`
- rename `neurom.view.common` to `neurom.view.matplotlib_utils`
- swap arguments `ax` and `nrn` of all plot functions in `neurom.view.matplotlib_impl`

### CODE REVIEW

**Comment by arnaudon** [comment]
Ah, I'm using this a lot, I hope it's not breaking to much! I'll take a proper look later.

**Comment by adrien-berchet** [comment]
That's a quite big breaking change for us indeed. Why do you want to change this?

**Comment by asanin-epfl** [comment]
Because `neurom.viewer` is an abstraction layer that complicates instead of simplifying:
- It introduces an additional layer of abstraction with magical `**kwargs` that are not documented, and can't be documented because it dynamically calls to different functions with different signatures. So, user has to go in the end to the underlying called function for documentation. This action completely kills the purpose of abstraction.
- it does not offer `plotly` option despite being an abstraction layer that tries to offer simpler API.

**Comment by adrien-berchet** [comment]
I see and I completely agree.
Nevertheless, we had a lot of breaking changes in NeuroM recently. It would be nice to gather them in one big new release when they are not urgent (this one does not seem urgent?). Or maybe you could add the new API that you propose but also keep the current API and raise a warning for future deprecation?

**Comment by arnaudon** [comment]
+1 for keeping both and put a deprecation warning, so we can have a smooth transition. I don't have time to look at this now, and I guess we could keep it this way and iterate over it on a few PRs/minor release to have a strong plotting module.

**Comment by arnaudon** [comment]
Remember, there is also this code: https://github.com/BlueBrain/plotly-helper

**Comment by asanin-epfl** [comment]
> Or maybe you could add the new API that you propose but also keep the current API and raise a warning for future deprecation?

I can keep `neurom.viewer` but other things get renamed. Will it be ok for you? Otherwise this PR can be put on hold for now.

**Comment by adrien-berchet** [comment]
As far as I can see it would only break NeuroR and synthesis-workflow (just 1 import to update), so I think it would be a good compromise for us if it's ok for you.

**Comment by jdcourcol** [comment]
The documentation contains examples with viewer. They have to be updated too.
Also the mybinder notebook has to be updated too.

**Comment by asanin-epfl** [comment]
@adrien-berchet, the merge of this branch will go into `2.4.0` branch instead of `master`. I will be collecting all further changes in the branch `2.4.0` as well. In a couple of weeks, I will merge `2.4.0` into `master`.

@jdcourcol thank you. I've updated notebooks and examples.

**Review by adrien-berchet — APPROVED** [review]
> @adrien-berchet, the merge of this branch will go into `2.4.0` branch instead of `master`. I will be collecting all further changes in the branch `2.4.0` as well. In a couple of weeks, I will merge `2.4.0` into `master`.

Looks like a very good plan, thank you very much!

**Pull request merged**
