### PR TITLE
init of config in morph_check

### PR DESCRIPTION
**Pull request by eleftherioszisis**

### CODE REVIEW

**Comment by juanchopanza** [comment]
Does this fix #168?

**Comment by eleftherioszisis** [comment]
Yes. This basically prevents the test function to break, and by extension throw an exception. This means that it does not do any tests, except from the valid soma which is not included and checked always.

**Comment by juanchopanza** [comment]
OK, good. I will merge it. Apparently, if you'd put "fixes #168" in the commit message, the issue would get closed when this gets merged. See https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by eleftherioszisis** [comment]
Ah, thanks for the link. I wasn't aware of that.

**Pull request merged**
