### PR TITLE
New features needed for validation / synthesis

### PR DESCRIPTION
**Pull request by lidakanari**
Prototypes on new -much needed- features, please optimize them when appropriate :)

### CODE REVIEW

**Comment by lidakanari** [comment]
Any idea why this is failing (since it has to do with the plots which were not modified to my knowledge). Also why does it repeat previous commits that I merged from the upstream?

**Comment by mgeplf** [comment]
Not sure, I will have to look into it.  Might be due to newer versions of dependent libraries.

**Comment by lidakanari** [comment]
Thanks! Let me know if I have to fix something....

**Comment by lidakanari** [comment]
@mgeplf thanks!

**Comment by mgeplf** [comment]
#595 is a copy of this, including a small change, so the changes are included.

**Pull request closed without merging**
