### PR TITLE
Update requirements.txt to include scipy.

### PR DESCRIPTION
**Pull request by lidakanari**
Minor change in requirements.txt

### CODE REVIEW

**Comment by juanchopanza** [comment]
Can you change the commit message? It is confusing because that requirement is commented out. It is only there for documentation purposes.

**Comment by lidakanari** [comment]
Agreed. Just please let me know how can I do this. 

I tried to 

git commit --amend -m "..."

but the push failed.

**Comment by juanchopanza** [comment]
I think you need a new commit. Or maybe you can edit the comment here.

**Comment by lidakanari** [comment]
Edited here. Let me know if it is more comprehensible now.

**Pull request merged**
