### PR TITLE
Add HBP funding acknowledgment and main authors file.

### PR DESCRIPTION
**Pull request by juanchopanza**

### CODE REVIEW

**Comment by juanchopanza** [comment]
@berthelm I added the HBP acknowledgement to the README (front page on github) and as a separate file. I am not sure if I should also add it to LICENSE.txt. Please let me know if I should.

**Comment by juanchopanza** [comment]
@lidakanari @eleftherioszisis @mgeplf I added you to the new AUTHORS.md file. Please let me know if that is OK with you, if you want your name to be hyperlinked to something, or if you have any other suggestions.

**Comment by berthelm** [comment]
I wondered that too (about adding it to the license text)  but I don't think we should. My reasoning is that the license is a legal statement about rights whereas the acknowledgements has less legal importance and is standalone. (IMHO)

**Comment by berthelm** [comment]
It looks good to me, please merge.
Thanks,
Julian

**Pull request merged**
