### PR TITLE
Fix 'section_path_lengths' feature for Population

### PR DESCRIPTION
**Pull request by asanin-epfl**
Solution for #926

### CODE REVIEW

**Review by adrien-berchet — APPROVED** [review]
Thanks!

**Comment by asanin-epfl** [comment]
Thank you! Do you need the release?

**Comment by adrien-berchet** [comment]
Yes please

**Comment by asanin-epfl** [comment]
> Yes please

done

**Comment by adrien-berchet** [comment]
Thanks :)

**Pull request merged**
