### PR TITLE
Include neuron filename extension into its name

### PR DESCRIPTION
**Pull request by asanin-epfl**
Solution to #786,

Useful for morph stats when morphologies differ only by file extension

### CODE REVIEW

**Review by adrien-berchet — APPROVED** [review]
LGTM
@arnaudon do you think it could break anything?

**Comment by arnaudon** [comment]
it may not break anything, but I'm not sure this is a good option, different file format should have the same answer in morph_stat. If we want to test the possible differences, one can name 'my_morph_asc.asc' and 'my_morph_swc.swc' to compare the, no?

**Comment by asanin-epfl** [comment]
> different file format should have the same answer in morph_stat.

Yes but it must not to overwrite one file extension with another. Besides there might be different morphologies under the same name with different extensions. Distinguishing among file extensions, will help user to detect this problem.


> If we want to test the possible differences, one can name 'my_morph_asc.asc' and 'my_morph_swc.swc' to compare the,

So, you manually added file extensions to names. How is that different from having file extensions?

**Comment by arnaudon** [comment]
Yes, this is a difficult thing to settle. My approach to it is to only distinguish morphologies by their names. I only work with a set of morphologies with consistent extensions, to avoid these issues. What I meant is that, if, as in the issue that triggered this PR, one want to extract morph_stats on 2 morphs with only a different extension (which is a very specific usecase I never had myself), one can change the names of the morphs to do that, instead of this PR. 
What I like to have in a df for morphologies, is a column name with just Path('morph.asc').stem, and a column with the path to that morph on disk (where the extension is written). But this is just my way of doing things, it may not be the best!

But you can merge that, and we'll see in practice. It possibly won't affect anything at all.

**Comment by asanin-epfl** [comment]
Thank you, I'm merging.

**Pull request merged**
