### PR TITLE
Update `neurom.features.get` docstring with available builtin features

### PR DESCRIPTION
**Pull request by eleftherioszisis**
Implements #1014 
Example resulting docstring:
```
Obtain a feature from a set of morphology objects.

Features can be either Neurite, Morphology or Population features. For Neurite features see
:mod:`neurom.features.neurite`. For Morphology features see :mod:`neurom.features.morphology`.
For Population features see :mod:`neurom.features.population`.

Arguments:
    feature_name(string): feature to extract
    obj: a morphology, a morphology population or a neurite tree
    kwargs: parameters to forward to underlying worker functions

Returns:
    List|Number: feature value as a list or a single number.

.. Builtin Features:

    Population
    ----------
    * sholl_frequency

    Morphology
    ----------
    * aspect_ratio
    * circularity
    * max_radial_distance
    * neurite_volume_density
    * number_of_neurites
    * number_of_sections_per_neurite
    * shape_factor
    * sholl_crossings
    * sholl_frequency
    * soma_radius
    * soma_surface_area
    * soma_volume
    * total_area_per_neurite
    * total_depth
    * total_height
    * total_length_per_neurite
    * total_volume_per_neurite
    * total_width
    * trunk_angles
    * trunk_angles_from_vector
    * trunk_angles_inter_types
    * trunk_origin_azimuths
    * trunk_origin_elevations
    * trunk_origin_radii
    * trunk_section_lengths
    * trunk_vectors
    * volume_density

    Neurite
    -------
    * bifurcation_partitions
    * diameter_power_relations
    * local_bifurcation_angles
    * max_radial_distance
    * number_of_bifurcations
    * number_of_forking_points
    * number_of_leaves
    * number_of_sections
    * number_of_segments
    * partition_asymmetry
    * partition_asymmetry_length


```

### CODE REVIEW

**Comment by eleftherioszisis** [comment]
If it is preferable it is also possible to print the signatures as well:

```
.. Builtin Features:

    Population
    ----------
    * sholl_frequency (morphs, neurite_type=<NeuriteType.all: 32>, step_size=10, bins=None)

    Morphology
    ----------
    * aspect_ratio (morph, neurite_type=<NeuriteType.all: 32>, projection_plane='xy')
    * circularity (morph, neurite_type=<NeuriteType.all: 32>, projection_plane='xy')
    * max_radial_distance (morph, neurite_type=<NeuriteType.all: 32>)
    * neurite_volume_density (morph, neurite_type=<NeuriteType.all: 32>)
    * number_of_neurites (morph, neurite_type=<NeuriteType.all: 32>)
    * number_of_sections_per_neurite (morph, neurite_type=<NeuriteType.all: 32>)
    * shape_factor (morph, neurite_type=<NeuriteType.all: 32>, projection_plane='xy')
    * sholl_crossings (morph, neurite_type=<NeuriteType.all: 32>, center=None, radii=None)
    * sholl_frequency (morph, neurite_type=<NeuriteType.all: 32>, step_size=10, bins=None)
    * soma_radius (morph)
    * soma_surface_area (morph)
    * soma_volume (morph)
    * total_area_per_neurite (morph, neurite_type=<NeuriteType.all: 32>)
    * total_depth (morph, neurite_type=<NeuriteType.all: 32>)
    * total_height (morph, neurite_type=<NeuriteType.all: 32>)
    * total_length_per_neurite (morph, neurite_type=<NeuriteType.all: 32>)
    * total_volume_per_neurite (morph, neurite_type=<NeuriteType.all: 32>)
    * total_width (morph, neurite_type=<NeuriteType.all: 32>)
    * trunk_angles (morph, neurite_type=<NeuriteType.all: 32>, coords_only='xy', sort_along='xy', consecutive_only=True)
    * trunk_angles_from_vector (morph, neurite_type=<NeuriteType.all: 32>, vector=None)
    * trunk_angles_inter_types (morph, source_neurite_type=<NeuriteType.apical_dendrite: 4>, target_neurite_type=<NeuriteType.basal_dendrite: 3>, closest_component=None)
    * trunk_origin_azimuths (morph, neurite_type=<NeuriteType.all: 32>)
    * trunk_origin_elevations (morph, neurite_type=<NeuriteType.all: 32>)
    * trunk_origin_radii (morph, neurite_type=<NeuriteType.all: 32>, min_length_filter=None, max_length_filter=None)
    * trunk_section_lengths (morph, neurite_type=<NeuriteType.all: 32>)
    * trunk_vectors (morph, neurite_type=<NeuriteType.all: 32>)
    * volume_density (morph, neurite_type=<NeuriteType.all: 32>)

    Neurite
    -------
    * bifurcation_partitions (neurite)
    * diameter_power_relations (neurite, method='first')

```

**Review by adrien-berchet — APPROVED** [review]
Nice!
I don't think the full signatures are needed, people can find it elsewhere in the doc. But maybe for sphinx we could add links to the doc of each feature to be super fancy?

**Comment by eleftherioszisis** [comment]
@adrien-berchet , these features are hidden from sphinx because of the `..` block. I wasn't sure if they should be added in the documentation of the get method.

**Comment by mgeplf** [comment]
@adrien-berchet > I don't think the full signatures are needed

I agree w/ this

@eleftherioszisis > I wasn't sure if they should be added in the documentation of the get method.

I think it would can be useful to have them.  Alternatively, a link to the morphio docs page w/ all the features?  I don't think that doing `help([...].get)`, and then clicking a link would be too bad.  Most of the time I need to look up what the feature actually does, except in the simplest named ones :)

I'm fine w/ the current PR though, and we can tweak it as required.

**Pull request merged**
