### PR TITLE
Cleanups and minor improvements.

### PR DESCRIPTION
**Pull request by juanchopanza**
* TreeType renamed to NeuriteType. Alias ezy.TreeType kept for
  backwards compatibility.
* neurom.geatures.get_feature added to neurom.ezy module.
* Documentation examples updated.
* Examples updated.

### CODE REVIEW

**Comment by juanchopanza** [comment]
This affects many files, but most changes are trivial, i.e. changing `TreeType` for `NeuriteType`. Note that `ezy.TreeType` is kept for backwards compatibility, and is an alias for `NeuriteType`.

The next step will be to remove or deprecate `ezy.neuron` functions whose functionality is already available from `neurom.features.get_feature`.

**Comment by eleftherioszisis** [comment]
Awesome! Is it possible that we have neurites instead of trees  for the neurons etc. and make a little more evident the underlying type injection that takes place in the making of a tree?

**Comment by juanchopanza** [comment]
Yes, I think so. We can discuss tomorrow or Friday.

**Comment by lidakanari** [comment]
Seems good to me!

**Pull request merged**
