### PR TITLE
Dev version 0.0.4.dev1

### PR DESCRIPTION
**Pull request by juanchopanza**

### CODE REVIEW

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by juanchopanza** [comment]
retest this please

**Comment by juanchopanza** [comment]
retest this please

**Comment by juanchopanza** [comment]
retest this please

**Comment by juanchopanza** [comment]
retest this please

**Comment by juanchopanza** [comment]
retest this please

**Pull request merged**
