### PR TITLE
Forgot to add the section number per neurite in the init

### PR DESCRIPTION
**Pull request by eleftherioszisis**

### CODE REVIEW

**Comment by juanchopanza** [comment]
Can we make this `nsections` or `number_of_sections`? `section_number` means something else to me. Like the number of a section.

**Comment by eleftherioszisis** [comment]
Sure.```number_of_sections``` is good and clear I think.

**Comment by eleftherioszisis** [comment]
If this is ok, can you merge it? I have another pull request waiting on the line. :P

**Comment by juanchopanza** [comment]
Done. You should probably use branches for separate features so you don't get blocked by pending merges. It is more involved than with gerrit, but it is workable.

**Pull request merged**
