### PR TITLE
Add neurom.viewer module with helper draw function.

### PR DESCRIPTION
**Pull request by juanchopanza**
Draws all kinds of morphologies in 2d, 3d, and dendrogram modes.

### CODE REVIEW

**Comment by juanchopanza** [comment]
I am wondering whether it is confusing to have `neurom.viewer` and `neurom.view`. Maybe everything can be put under one single module, maintaining the top level functionality shown here. The question would then be, which name? `viewer` or `view`? @lidakanari @eleftherioszisis any thoughts?

**Comment by lidakanari** [comment]
I agree that it is confusing to have both. I guess we should be consistent with the general code: do we prefer verbs or nouns? Also, we should consider the view.draw and viewer.draw which will be available to the user. I guess the second one sounds a little bit better, but this is just a matter of personal taste...

**Comment by juanchopanza** [comment]
I was thinking the same. `view.draw` sounds like two verbs (even if both words can also be nouns.) How about adding this as it is right now, and then moving the stuff from `neurom.view` into  `neurom.viewer` module at a later stage?

**Comment by lidakanari** [comment]
No problem for me.

**Comment by juanchopanza** [comment]
OK, maybe we can discuss naming tomorrow.

**Pull request merged**
