### PR TITLE
Fix show plot in python mode

### PR DESCRIPTION
**Pull request by lidakanari**
This should fix issue #210

### CODE REVIEW

**Comment by juanchopanza** [comment]
I'll merge this, when @wvangeit can confirm if it fixed the issue.

**Comment by wvangeit** [comment]
Ok, thanks, it works. (Although at the moment I tried, the new version was not pushed to pypi yet)

**Comment by juanchopanza** [comment]
Fixes #210.

**Comment by juanchopanza** [comment]
@wvangeit We're only putting releases on pypi. I will make a new release (v 0.0.13) soon.

**Pull request merged**
